server:
  port: ${PORT:8080}
logging:
  level:
    org.atmosphere: warn

spring:
  mustache:
    check-template-location: false

vaadin:
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,be.archilios.usermanagement
  launch-browser: true